server:
  port: 8001

spring:
  application:
    name: springcloud-pay
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://47.110.38.195:3306/spring-cloud-pay?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: simon
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.ksshop.pay.entities       #所有Entity别名类所在包